apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sumo-stage-web
  namespace: sumo-stage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sumo-stage-web
  minReplicas: 4
  maxReplicas: 12
  targetCPUUtilizationPercentage: 60
